export const constants = {
  SIGNUP: 'Sign Up',
  FIRST_NAME_PLACEHOLDER: 'First Name',
  LAST_NAME_PLACEHOLDER: 'Last Name',
  EMAIL_ADDRESS_PLACEHOLDER: 'Email',
  PASSWORD_PLACEHOLDER: 'Password',
  CONFIRM_PASSWORD_PLACEHOLDER: 'Confirm Password',
  AGREE_TEXT: 'I agree all',
  TERMS_TEXT: 'Terms & Conditions',
  ALREADY_ACCOUNT: 'Already have an account?',
  LOGIN: 'Login',
  CHECKBOX_ERROR: 'Please agree to Terms & Conditions',
  API_ENDPOINT: '/api/v1/auth',
  EMAIL_EXISTS_ERROR: 'Email already exist',
  EMAIL_TAKEN: 'Email has already been taken',
  FIRST_NAME_KEY: 'firstName',
  LAST_NAME_KEY: 'lastName',
  EMAIL_KEY: 'email',
  PASSWORD_KEY: 'password',
  CONFIRM_PASSWORD_KEY: 'confirmPassword',
};
