export const constants = {
    COOKIE_POLICY: "Cookies Policy",
    COOKIE_POLICY_CONTENT: "Like any other website, LearnEazee uses 'cookies. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.",
    GOOGLE_DART: "Google DoubleClick DART Cookie",
    GOOGLE_DART_CONTENT: "Google is one of the third-party vendors on our site. It also uses cookies, known as DART cookies, to serve ads to our site visitors based upon their visit to www.website.com and other sites on the internet. However, visitors may choose to decline the use of DART cookies by visiting the Google ad and content network Privacy Policy at the following URL – https://policies.google.com/technologies/ads",
    ADVERTISING: "Our Advertising Partners",
    ADVERTISING_CONTENT: "Some of the advertisers on our site may use cookies and web beacons. Our advertising partners are listed below. Each of our advertising partners has its Privacy Policy for its policies on user data. For easier access, we hyperlinked to their Privacy Policies below. Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on LearnEazee, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit. Note that LearnEazee has no access to or control over these cookies that are used by third-party advertisers.",
    THIRD_PARTY: "Third-Party Privacy Policies",
    THIRD_PARTY_CONTENT: "LearnEazee's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt out of certain options. You can choose to disable cookies through your browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites. What Are Cookies?",
    CHILD_INFO: "Children's Information",
    CHILD_INFO_CONTENT: "Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity. LearnEazee does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.",
    ONLINE_POLICY: "Online Privacy Policy Only",
    ONLINE_POLICY_CONTENT: "This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in LearnEazee. This policy does not apply to any information collected offline or via channels other than this website.",
}